address/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/login', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . views import ContactListView, ContactCreateView, ContactUpdateView, ContactDeleteView
from . import views


app_name = 'users'

urlpatterns = [
    path('register', views.user_signup, name='user-signup'),
    path('', ContactListView.as_view(), name='contact-index'),
    path('contact-create/', ContactCreateView.as_view(), name='contact-create'),
    path('<int:pk>/contact-update/', ContactUpdateView.as_view(), name='contact-update'),
    path('<int:pk>/contact-delete/', ContactDeleteView.as_view(), name='contact-delete'),
]

users/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=45)
    is_male = models.BooleanField(default=True)
    cover = models.FileField()
    email = models.EmailField()
    telephone = models.CharField(max_length=12)
    relation = models.CharField(max_length=45)
    residence = models.CharField(max_length=50)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('users:contact-index')

users/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        help_texts = None

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Contact
from django.contrib.auth.mixins import LoginRequiredMixin
from . forms import UserForm
from django.contrib.auth import authenticate, login


# Create your views here.
class ContactListView(LoginRequiredMixin, ListView):
    model = Contact
    context_object_name = 'contacts'
    template_name = 'users/index.html'
    ordering = ['name']

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)


class ContactCreateView(CreateView):
    model = Contact
    fields = ['name', 'email', 'telephone', 'relation', 'residence', 'cover', 'is_male']
    template_name = 'users/create_contact.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ContactUpdateView(UpdateView):
    model = Contact
    fields = ['name', 'email', 'telephone', 'relation', 'residence', 'cover', 'is_male']
    template_name = 'users/create_contact.html'


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = '/'


def user_signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('users:contact-index')
    return render(request, 'registration/register.html', {'form': form})

users/templates/users/base.html
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
<div class="container-fluid">
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'users:contact-index' %}" style="color: steelblue;"><i class="fas fa-user"></i> Contacts</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-5">
<li class="nav-item">
        <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
        </form>
        </li>
    </ul>

      <ul class="navbar-nav navbar-right">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'users:contact-create' %}"><i class="fas fa-plus"></i> Add contact</a>
      </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
          </li>
          {% endif %}
      
    </ul>

  </div>
</nav>
</div>
<div class="container">
    {% block content %}

    {% endblock %}
{% include 'users/footer.html' %}


</div>



</body>
</html>

users/templates/users/contact_confirm_delete.html
{% extends 'users/base.html' %}
{% block title %}Delete {{ object.name }}{% endblock %}

{% block content %}
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="card card-body">

<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Contact</legend>
        <h4>Are you want to Delete "{{ object.name }}"</h4>
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{% url 'users:contact-index' %}">Cancel</a>
    </div>
</form>

        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/create_contact.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% if object %}Update {{ object.name }}{% else %}New contact{% endif %}{% endblock %}

{% block content %}
    <br>
    <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
    <div class="card card-body">
        <h4 class="text-info ml-5">{% if object %}Update {{ object.name }}{% else %}Add Contact{% endif %}</h4><hr>
        <form class="form-horizontal mr-5 ml-5" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-info">{% if object %}Update{% else %}Submit{% endif %}</button>
            </div>
        </form>
    </div>
    </div>
    </div>
{% endblock %}

users/templates/users/footer.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<div class="container-fluid">
    <div class="row" style="padding-top: %;">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <hr>
        <p class="text-center"><i class="fas fa-copyright"></i> kodenaut</p>
        </div>
    </div>
</div>

users/templates/users/index.html
{% extends 'users/base.html' %}

{% block title %}My contacts{% endblock %}

{% block content %}
    <br>
<div class="row">
{% if contacts %}
    {% for contact in contacts %}
        <div class="col-sm-3 {% if contact.is_male %}text-primary {% else %}text-danger{% endif %} my-1">
            <img src="{{ contact.cover.url }}" class="img img-responsive" alt="" style="height: 30%; width: 100%;">
            <div class="card">
            <div class="card-header" style="color:white; background-color:{% if contact.is_male %}darkblue;{% else %}red;{% endif %}">
                <p class="p-item"><i class="{% if contact.is_male %}fas fa-mars{% else %}fas fa-venus{% endif %}"></i>&nbsp; {{ contact.name }}</p>
            </div>
            <div class="card-body">
                    <p class="p-item"><i class="fas fa-envelope"></i> {{ contact.email }}</p>
                    <p class="p-item"><i class="fas fa-phone"></i> {{ contact.telephone }}</p>
                    <p class="p-item"><i class="fas fa-user-circle"></i> {{ contact.relation }}</p>
                    <p class="p-item"><i class="fas fa-globe"></i> {{ contact.residence }}</p>
                <a href="{% url 'users:contact-update' contact.id %}" class="btn btn-info btn-xs">
                    <span class="fas fa-edit"></span>&nbsp;
                </a>
                <a href="{% url 'users:contact-delete' contact.id %}" class="btn btn-danger btn-xs">
                    <span class="fas fa-trash"></span>&nbsp;
                </a>

                </div>
        </div>
        </div>
    {% endfor %}

    {% else %}
    <div class="container" style="padding-top: 7%;">
    <div class="row pt-5">
    <div class="col-sm-4">
    <div class="card card-body">
        <i class="text-center fas fa-book-open fa-2x"></i>
        <hr>
        <p class="text-center">This Applications lets you create your contacts and store them.</p>
    </div>
    </div>

    <div class="col-sm-4">
    <div class="card card-body">
        <i class="text-center fas fa-users fa-2x"></i>
        <hr>
        <p class="text-center">The Application lets you categorize your contacts as friends, family or colleagues.</p>
    </div>
    </div>

    <div class="col-sm-4">
    <div class="card card-body">
        <i class="text-center fas fa-envelope fa-2x"></i>
        <hr>
        <p class="text-center">The Application enables you to send messages to your contacts.</p>
    </div>
    </div>
    </div>
    </div>
{% endif %}



</div>
{% endblock %}